spring.application.name=projecte2
spring.profiles.active=local

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.sql.init.mode=always